### ISSUE TITLE
Cannot open load file "gtk-style-ext-sys"

### ISSUE THREAD

**Issue by liferooter** [Soft/emacs-gtk-style-ext#1]
# My software
**OS**: Gentoo Linux
**Emacs version**: 27.0.91

# Steps to reproduce
1. Install gtk-style-ext-sys
2. Open Emacs
3. Open scratch buffer
4. Type: ```
(require 'gtk-style-ext)```
5. Press C-j

# Bug

Elisp debugger returns error:
```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "Нет такого файла или каталога" "gtk-style-ext-sys")
  require(gtk-style-ext-sys)
  eval-buffer(#<buffer  *load*> nil "/usr/share/emacs/site-lisp/gtk-style-ext.el" nil t)  ; Reading at buffer position 992
  load-with-code-conversion("/usr/share/emacs/site-lisp/gtk-style-ext.el" "/usr/share/emacs/site-lisp/gtk-style-ext.el" nil t)
  require(gtk-style-ext)
  (progn (require 'gtk-style-ext))
  eval((progn (require 'gtk-style-ext)) t)
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp(nil)
  funcall-interactively(eval-print-last-sexp nil)
  call-interactively(eval-print-last-sexp nil nil)
  command-execute(eval-print-last-sexp)
```

UPD. I am Russian

**Comment by Soft** [comment]
gtk-style-ext module requires a native emacs module gtk-style-ext-sys in order to work. Are you sure you have `gtk-style-ext-sys.so` file somewhere in your emacs load path? Maybe in the `/usr/share/emacs/site-lisp/` directory. Based on the error message it seems like emacs cannot find this file.

**Comment by liferooter** [comment]
Yes, I sure. I have `/usr/share/emacs/site-lisp/gtk-style-ext-sys.so` and `/usr/share/emacs/site-lisp/gtk-style-ext-sys.la`

**Comment by Soft** [comment]
Hmm that's really odd, then it's not clear to me why it can't find the module. If you are using Gentoo, did you install emacs with dynamic-loading USE flag enabled?

**Comment by liferooter** [comment]
Yes, thanks. It was fixed by recompiling with this option. It just my mistake. Sorry
